### ISSUE TITLE
Possible to connect to multiple streams at once?

### ISSUE THREAD

**Issue by fatduckling** [independentreserve/websockets#1]
Hi
Is it possible to subscribe to multiple order books or tickers without having to open multiple websocket connections?

For example, I want to see the order book for XBT/AUD and LTC/AUD. Do I have to open two connections to accomplish this?

wss://websockets.independentreserve.com/orderbook-xbt-aud
wss://websockets.independentreserve.com/orderbook-ltc-aud

Thanks

**Comment by stefanidi** [comment]
We have changed to a subscription model, you can subscribe to multiple channels on one feed now.
